language: objective-c

reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c

podfile: Examples/iOS/Podfile

before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - gem install cocoapods --no-ri --no-rdoc

script:
  - xctool -workspace Examples/iOS/A0SimpleKeychain.xcworkspace -scheme A0SimpleKeychain -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO clean test

notifications:
  slack:
    secure: AXLozZlImcdopg/+srq4wcC4SVGMmoDJDXR1PKrH+Dc7DtnYXLCOKKk8hAXySIiHGR4820CX1SZ25By1Q6l8GIomHMfbYwdPILG61KHbIMydBIeoLUNRlM+VK6ao5uFt0Fj6ByNYMQweUuXDAHli88mHwE1aJmL7K3unn11L0lU=

branches:
  only:
    - master
